### ISSUE TITLE
Set parameter from nested object

### ISSUE THREAD

**Issue by danihodovic** [jskopek/django-query-parameters#4]
The following doesn't seem to work as django-query-parameters interprets nested object access as a string.

```html
{% set_query_parameters recipients=request.GET.recipients %}
```

Outcome: `?recipients=request.GET.recipients`
Expected outcome: `?recipients=<nested-value>`

Also is it possible to turn off urlencoding https://github.com/jskopek/django-query-parameters/blob/master/query_parameters/templatetags/query_parameters.py#L73

**Comment by jskopek** [comment]
Hey danihodovic

I’ll have a look at this to see if there’s anything that can be done to make it work a little better out the box. In the meantime, would something like this work?

`{% with request.get.recipients as recipients %}{% set_query_parameters recipients=recipients %}{% endwith %}`

**Comment by danihodovic** [comment]
Yup that works.

**Comment by jskopek** [comment]
Hello @danihodovic 

I did a little more experimenting, and it looks like the template tag should theoretically work as you are expecting. `{% set_query_parameters %}` accepts dictionary values (e.g. `{% set_query_parameters query5=request.GET.query4 %}` works).

I can recreate the issue you were seeing when a path is provided to a dictionary value that does not exist. For example, `request.GET.recipients` will have the value of the `recipients` query string if it is present, but will show `request.GET.recipients` if it is not. This is done so that constant string values can be provided as parameters to the template tag (e.g. `{% set_query_parameters order_by=name %}`). My recommendation for this scenario is to set a context variable for `recipients` in your view and refer to that value.

Hope this helps!
